# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /thayerfs/home/f0062gt/workspace/module2/module2.srcs/sources_1/bd/module2_hw/ip/module2_hw_axi_gpio_2_0/module2_hw_axi_gpio_2_0.xci
# IP: The module: 'module2_hw_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f0062gt/workspace/module2/module2.gen/sources_1/bd/module2_hw/ip/module2_hw_axi_gpio_2_0/module2_hw_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'module2_hw_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f0062gt/workspace/module2/module2.gen/sources_1/bd/module2_hw/ip/module2_hw_axi_gpio_2_0/module2_hw_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module2_hw_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f0062gt/workspace/module2/module2.gen/sources_1/bd/module2_hw/ip/module2_hw_axi_gpio_2_0/module2_hw_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'module2_hw_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /thayerfs/home/f0062gt/workspace/module2/module2.srcs/sources_1/bd/module2_hw/ip/module2_hw_axi_gpio_2_0/module2_hw_axi_gpio_2_0.xci
# IP: The module: 'module2_hw_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f0062gt/workspace/module2/module2.gen/sources_1/bd/module2_hw/ip/module2_hw_axi_gpio_2_0/module2_hw_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'module2_hw_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f0062gt/workspace/module2/module2.gen/sources_1/bd/module2_hw/ip/module2_hw_axi_gpio_2_0/module2_hw_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module2_hw_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f0062gt/workspace/module2/module2.gen/sources_1/bd/module2_hw/ip/module2_hw_axi_gpio_2_0/module2_hw_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'module2_hw_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
