# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/module2_hw/module2_hw.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module2_hw || ORIG_REF_NAME==module2_hw} -quiet] -quiet

# IP: bd/module2_hw/ip/module2_hw_processing_system7_0_0/module2_hw_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module2_hw_processing_system7_0_0 || ORIG_REF_NAME==module2_hw_processing_system7_0_0} -quiet] -quiet

# IP: bd/module2_hw/ip/module2_hw_axi_gpio_0_0/module2_hw_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module2_hw_axi_gpio_0_0 || ORIG_REF_NAME==module2_hw_axi_gpio_0_0} -quiet] -quiet

# IP: bd/module2_hw/ip/module2_hw_xbar_0/module2_hw_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module2_hw_xbar_0 || ORIG_REF_NAME==module2_hw_xbar_0} -quiet] -quiet

# IP: bd/module2_hw/ip/module2_hw_ps7_0_axi_periph_0/module2_hw_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module2_hw_ps7_0_axi_periph_0 || ORIG_REF_NAME==module2_hw_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/module2_hw/ip/module2_hw_rst_ps7_0_50M_0/module2_hw_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module2_hw_rst_ps7_0_50M_0 || ORIG_REF_NAME==module2_hw_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/module2_hw/ip/module2_hw_axi_gpio_1_0/module2_hw_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module2_hw_axi_gpio_1_0 || ORIG_REF_NAME==module2_hw_axi_gpio_1_0} -quiet] -quiet

# IP: bd/module2_hw/ip/module2_hw_axi_gpio_2_0/module2_hw_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module2_hw_axi_gpio_2_0 || ORIG_REF_NAME==module2_hw_axi_gpio_2_0} -quiet] -quiet

# IP: bd/module2_hw/ip/module2_hw_xlconcat_0_0/module2_hw_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module2_hw_xlconcat_0_0 || ORIG_REF_NAME==module2_hw_xlconcat_0_0} -quiet] -quiet

# IP: bd/module2_hw/ip/module2_hw_auto_pc_0/module2_hw_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==module2_hw_auto_pc_0 || ORIG_REF_NAME==module2_hw_auto_pc_0} -quiet] -quiet

# XDC: /thayerfs/home/f0062gt/workspace/module2/module2.gen/sources_1/bd/module2_hw/module2_hw_ooc.xdc
