# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /thayerfs/home/f0062gt/workspace/module2/module2.srcs/sources_1/bd/module2_hw/ip/module2_hw_xbar_0/module2_hw_xbar_0.xci
# IP: The module: 'module2_hw_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f0062gt/workspace/module2/module2.gen/sources_1/bd/module2_hw/ip/module2_hw_xbar_0/module2_hw_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module2_hw_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /thayerfs/home/f0062gt/workspace/module2/module2.srcs/sources_1/bd/module2_hw/ip/module2_hw_xbar_0/module2_hw_xbar_0.xci
# IP: The module: 'module2_hw_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f0062gt/workspace/module2/module2.gen/sources_1/bd/module2_hw/ip/module2_hw_xbar_0/module2_hw_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'module2_hw_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
